### ISSUE TITLE
Feature request: remove lyrics subtitles

### ISSUE THREAD

**Issue by tunjan** [Ajatt-Tools/impd#2]
Add an option (i.e: impd add -l) to remove the openings and endings from subtitles.

rg -n -B2 "pattern" file | cut  -f1 -d: | sed 's/-.*//' | sed '/^$/d'

This script would output the line of the music pattern + two lines before (in case the mime type is srt).

sed -i '${line}d' output.srt

This one would delete the lines outputed by the previous command.

**Comment by tatsumoto-ren** [comment]
Is it fixed now?

**Comment by tunjan** [comment]
Yes, works flawlessly. Thank you.
