### ISSUE TITLE
Cannot get impd rotate/condense to work

### ISSUE THREAD

**Issue by larkalfen04** [Ajatt-Tools/impd#6]
I installed `mpd` `mpc` `impd` `ncmpcpp` in
my system MacOS Monterey 12.6.2

When I tried try impd rotate. It does not work and outputted this.
```
Archiving old episodes...
Nothing to archive.
Updating DB (#16) ...
volume: 30%   repeat: off   random: off   single: off   consume: off
A playlist longer than 1 song in length is required to crop.
volume: 30%   repeat: off   random: off   single: off   consume: off
volume: 30%   repeat: off   random: off   single: off   consume: off
```

I tried to condense one video file (.mp4) with external .srt. But end up in error like this.

```
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
Error: filename should end with '.ogg'
```

Thank you for your help. I am not used with code stuff like this. I am more used to web programming 😅

**Comment by tatsumoto-ren** [comment]
I'm not sure if `impd` has ever been tested on macOS to be honest. If you're the first, it's your noble task to investigate the problem and find a solution 💪.  I have never used macOS and have never owned an Apple device so it's unlikely that I will be able to help. 

Based on the [errors](https://www.google.co.jp/search?hl=ja&q=%22illegal+option+--+-%22) you've provided my guess would be that the version of `Bash` used in macOS is different from the version of Bash used in the GNU operating system, and they're not compatible. 

If it is possible, try installing a different version of Bash from something like Homebrew.

**Comment by larkalfen04** [comment]
First of all, I figured out that `mktemp` behaves differently here. I need to remove `--tmpdir` argument because it already points to /tmp folder

Then,
I updated mine to Bash 5.2.15 after I encountered some 'bad substitution' error on this line

```
guess_track_priority() {
	# Sets some numeric weight for track. Used when sorting tracks.
	local -r track_lang=${1,,} track_title=${2,,}
```

Now I only have this error
`Error: filename should end with '.ogg'`
When I tried to print `$output` it returns empty string

Note:
Previously there is also difference in `grep` that I encountered. Turns out I have to use `ggrep` that I get from Homebrew

**Update**
I had suspicion that `readlink` may be the culprit here. I tried to install `coreutils` from Homebrew and use `greadlink` instead.
Now it works like a charm 🥳

**Comment by tatsumoto-ren** [comment]
Good news!
